services:
  app:
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/laravel
    ports:
      - '8000:8000'
    command: >
      sh -lc "php artisan serve --host 0.0.0.0 --port 8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=database_test_server
      - DB_USERNAME=root
      - DB_PASSWORD=root
  node:
    image: node:20
    working_dir: /var/www/laravel
    command: sh -lc "npm ci && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./laravel:/var/www/laravel
      - node_modules:/var/www/laravel/node_modules
    depends_on: [ app ]
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_test_server
    ports:
      - '3316:3306'
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
  node_modules:
